const fallbackScenario={id:'novatech-achats-001',title:'Crise fournisseur chez Novatech Industries',durationMinutes:45,mission:"Sécuriser l'approvisionnement, préparer la négociation et recommander une décision argumentée à la direction générale.",initialFacts:["Le fournisseur stratégique annonce une hausse tarifaire de 18 %.","Il représente 62 % des approvisionnements de cette famille.","Le stock disponible couvre 19 jours.","La direction générale refuse une hausse supérieure à 5 %."],characters:[{id:'supplier',name:'Marc Delcourt',role:'Directeur commercial du fournisseur',knownFacts:['Les coûts énergie et transport ont augmenté.','La marge réelle permet une négociation partielle.']},{id:'cfo',name:'Sophie Martin',role:'Directrice financière',knownFacts:['Chaque point de hausse a un impact direct sur la marge de la gamme.']},{id:'production',name:'Karim Benali',role:'Directeur de production',knownFacts:["Une rupture de plus de deux jours perturberait fortement le planning."]},{id:'quality',name:'Claire Roux',role:'Responsable qualité',knownFacts:["La qualification d'une source alternative demande normalement plusieurs semaines."]},{id:'ceo',name:'Thomas Leroy',role:'Directeur général',knownFacts:["Une hausse supérieure à 5 % n'est pas acceptable sans contreparties fortes."]}],events:[{id:'supplier-stop',title:'Arrêt de production fournisseur',trigger:{type:'turn',value:4},reveals:["Le fournisseur annonce un arrêt de production de trois semaines."]},{id:'sales-growth',title:'Nouvelle opportunité commerciale',trigger:{type:'turn',value:8},reveals:["Le commerce annonce une opportunité susceptible d'augmenter les volumes de 20 %."]}],skills:['diagnostic','investigation','questioning','verification','critical-thinking','decision-making','adaptability','communication','ai-collaboration']};

const $=id=>document.getElementById(id);let scenario;let active;let turns=0;let fired=new Set();let remaining=45*60;let recognition=null;let listening=false;

async function loadScenario(){try{const r=await fetch('../../examples/novatech-achats-simulation.json');if(!r.ok)throw new Error();scenario=await r.json()}catch{scenario=fallbackScenario}remaining=(scenario.durationMinutes||45)*60;renderScenario();selectCharacter(scenario.characters[0].id);tick();setInterval(tick,1000)}
function renderScenario(){$('scenarioTitle').textContent=scenario.title;$('mission').textContent=scenario.mission;$('facts').innerHTML=scenario.initialFacts.map(f=>`<li>${escapeHtml(f)}</li>`).join('');$('factCount').textContent=`${scenario.initialFacts.length} faits`;$('characters').innerHTML=scenario.characters.map((c,i)=>`<button class="character" data-id="${c.id}" type="button"><div class="avatar">${escapeHtml(c.name.split(' ').map(x=>x[0]).slice(0,2).join(''))}</div><strong>${escapeHtml(c.name)}</strong><span>${escapeHtml(c.role)}</span></button>`).join('');document.querySelectorAll('.character').forEach(b=>b.addEventListener('click',()=>selectCharacter(b.dataset.id)));$('skills').innerHTML=scenario.skills.map(s=>`<span class="skill-chip">${escapeHtml(labelSkill(s))}</span>`).join('')}
function selectCharacter(id){active=scenario.characters.find(c=>c.id===id);document.querySelectorAll('.character').forEach(b=>b.classList.toggle('active',b.dataset.id===id));$('activeName').textContent=active.name;$('activeRole').textContent=active.role;addMessage('system',`Vous échangez maintenant avec ${active.name}, ${active.role}.`)}
function addMessage(kind,text,meta=''){const d=document.createElement('div');d.className=`message ${kind}`;d.innerHTML=`${escapeHtml(text)}${meta?`<small>${escapeHtml(meta)}</small>`:''}`;$('conversation').appendChild(d);$('conversation').scrollTop=$('conversation').scrollHeight}
function characterReply(text){const q=text.toLowerCase();let answer;if(q.includes('pourquoi')||q.includes('18')||q.includes('hausse')) answer=active.knownFacts?.[0]||'Je peux vous préciser mon point de vue si vous ciblez votre question.';else if(q.includes('risque')||q.includes('rupture')||q.includes('stock')) answer=active.knownFacts?.find(f=>/rupture|qualification|hausse/i.test(f))||active.knownFacts?.[0]||'Il existe un risque, mais je souhaite que vous précisiez lequel vous analysez.';else if(q.includes('alternative')||q.includes('fournisseur')) answer=active.id==='quality'?active.knownFacts[0]:'Quelles garanties attendez-vous avant d’envisager une alternative ?';else answer=`Je comprends votre question. De mon point de vue de ${active.role.toLowerCase()}, ${active.knownFacts?.[0]?.charAt(0).toLowerCase()+active.knownFacts?.[0]?.slice(1)||'j’ai besoin que vous précisiez votre analyse'}`;setTimeout(()=>{addMessage('agent',answer,active.name);speak(answer);advanceTurn()},450)}
function advanceTurn(){turns++;scenario.events.forEach(e=>{if(e.trigger?.type==='turn'&&turns>=e.trigger.value&&!fired.has(e.id)){fired.add(e.id);const text=e.reveals.join(' ');const card=document.createElement('div');card.className='event-card';card.innerHTML=`<strong>⚠ ${escapeHtml(e.title)}</strong>${escapeHtml(text)}`;$('events').querySelector('.muted')?.remove();$('events').appendChild(card);addMessage('system',`${e.title} — ${text}`)}})}
$('messageForm').addEventListener('submit',e=>{e.preventDefault();const text=$('messageInput').value.trim();if(!text)return;addMessage('user',text,'Vous');$('messageInput').value='';characterReply(text)});
$('textMode').onclick=()=>setMode('text');$('voiceMode').onclick=()=>setMode('voice');
function setMode(mode){const voice=mode==='voice';$('textMode').classList.toggle('active',!voice);$('voiceMode').classList.toggle('active',voice);$('voicePanel').classList.toggle('hidden',!voice);$('messageForm').classList.toggle('hidden',voice);if(voice)prepareVoice()}
function prepareVoice(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){$('voiceState').textContent='Reconnaissance vocale non disponible';$('voiceHelp').textContent="Le navigateur actuel ne fournit pas l'API de reconnaissance vocale. Le mode texte reste disponible.";$('micButton').disabled=true;return}if(recognition)return;recognition=new SR();recognition.lang='fr-FR';recognition.interimResults=false;recognition.continuous=false;recognition.onstart=()=>{listening=true;$('micButton').classList.add('listening');$('voiceState').textContent='Je vous écoute…'};recognition.onend=()=>{listening=false;$('micButton').classList.remove('listening');$('voiceState').textContent='Appuyez pour parler'};recognition.onerror=()=>{$('voiceHelp').textContent='La prise de parole a été interrompue. Vous pouvez réessayer.'};recognition.onresult=e=>{const text=e.results[0][0].transcript;addMessage('user',text,'Vous · voix');characterReply(text)}}
$('micButton').onclick=()=>{prepareVoice();if(!recognition)return;if(listening)recognition.stop();else recognition.start()};
function speak(text){if(!$('voiceMode').classList.contains('active')||!('speechSynthesis'in window))return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='fr-FR';u.rate=.98;window.speechSynthesis.speak(u)}
$('submitDecision').onclick=()=>{const h=$('hypothesis').value.trim(),d=$('decision').value.trim(),e=$('evidence').value.trim();if(!d){$('decision').focus();return}$('decisionSummary').textContent=`Diagnostic\n${h||'Non renseigné'}\n\nDécision\n${d}\n\nÉléments de preuve\n${e||'Non renseignés'}\n\nInteractions réalisées : ${turns}`;$('decisionDialog').showModal()};$('closeDialog').onclick=()=>$('decisionDialog').close();
function tick(){remaining=Math.max(0,remaining-1);const m=String(Math.floor(remaining/60)).padStart(2,'0'),s=String(remaining%60).padStart(2,'0');$('timer').textContent=`${m}:${s}`;if(!remaining)$('sessionStatus').textContent='Temps écoulé'}
function labelSkill(s){return({'critical-thinking':'Esprit critique','decision-making':'Décision','ai-collaboration':'Collaboration IA',questioning:'Questionnement',verification:'Vérification',diagnostic:'Diagnostic',investigation:'Investigation',adaptability:'Adaptation',communication:'Communication'})[s]||s}
function escapeHtml(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
loadScenario();
